services:
  account.notifications.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5089:8080"
      - "7098:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./src/Account.Notifications.WebApi/appsettings.Development.json:/app/appsettings.Development.json


  account.identity.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5090:8080"
      - "7099:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./src/Account.Identity.GrpcService/appsettings.Development.json:/app/appsettings.Development.json


  elasticsearch:
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"


  logstash:
    volumes:
      - ./Hosting/Local/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "5000:5000"


  kibana:
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200


  filebeat:
    user: root
    volumes:
      - ./logs:/app/logs:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock


  grafana:
    ports:
      - "3000:3000"


  prometheus:
    ports:
        - "9090:9090"
    volumes:
        - ./Hosting/Local/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml


  kafka:
    ports:
      - "29092:29092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      CLUSTER_ID: "asdqwe@asde3sdSDFWEdasd2213"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3


  kafka-ui:
    ports:
      - "8080:8080"
    environment:
        KAFKA_CLUSTERS_0_NAME: local
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
        KAFKA_CLUSTERS_0_KRAFT_ENABLED: "true"
        KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT


  mongo1:
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
    environment:
      - MONGO_INITDB_REPLICA_SET_NAME=rs0


  mongo2:
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db
    environment:
      - MONGO_INITDB_REPLICA_SET_NAME=rs0


  mongo3:
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db
    environment:
      - MONGO_INITDB_REPLICA_SET_NAME=rs0


volumes:
  elasticsearch_data:
  kafka_data:  
  mongo1_data:
  mongo2_data:
  mongo3_data:  